# CI trigger
trigger:
- master

# PR trigger
pr:
- master

queue:
  name: Hosted VS2017
  demands: npm
  timeoutInMinutes: 15

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.4'
  displayName: 'Use Node version'

- script: |
    npm install
    npm run build
    npm run test
  displayName: 'npm install, build and test'
